### ISSUE TITLE
Retro Final.

### ISSUE THREAD

**Issue by nbxandresvejar** [lopar711/challenge_neubox#3]
Resultados: Oscar Garcia
Retro final:

Problema 1: PHP
1.- No se puede probar dado que existe el path del archivo en código duro, se puede haber utilizado argumentos para poder entregar el archivo.
    ej: $filename = $argv[1];
Aún cuando se realizó el fix para poder probar existen escenarios no cubiertos.
Como recomendación hay que poner atención a los detalles de los problemas.

Escenarios:
P1-CP1-EntradaEjemplo: Fail.
    Se especifica:  (Nota: Ninguna instrucción en el libro de instrucciones contiene dos letras iguales seguidas)
P1-CP1-EntradaCorrecta: Pass
P1-CP2-LongitudLinea1Invalida: Pass
P1-CP3-LongitudLinea2Invalida: Pass
P1-CP4-LongitudMensajeInvalido: Pass
P1-CP5-LongitudMensajeMenor3: Pass
P1-CP6-LongitudMensajeMayor5000: Pass
P1-CP7-LongitudInstruccion1Menor2: Pass
P1-CP8-LongitudInstruccion2Menor2: Pass
P1-CP9-CaracteresInvalidosMensaje: Pass
P1-CP10-LongitudInstruccion1Mayor50: Pass
P1-CP11-LongitudInstruccion2Mayor50: Pass
P1-CP12-DosInstruccionesEnMensaje: Fail
    Se especifica: Máximo existe una instrucción escondida por mensaje aunque es posible que no haya ninguna instrucción en el mensaje.
P1-CP13-InstruccionCaracterRepetido: Fail
    Mismo escenario P1-CP1-EntradaEjemplo

Problema 2: PHP
- El problema no realiza ninguna actividad dado que no tiene punto de entrada. El código está comentado.
- El problema no está correctamente resuelto, dado que se especifica lo siguiente:
    - Al final de cada ronda se observa el acumulado de la puntuación y la diferencia. Al terminar el juego quien gana es aquel que haya conseguido la mayor ventaja
    - El resultado no realiza el acumulado para determinar al ganador

**Comment by lopar711** [comment]
Entendido, gracias por la retro, ahora que veo el resultado de los test y tus indicaciones me doy cuenta que me apresuré y no analicé a detalle el problema, tus comentarios todos válidos, error mio totalmente, lamento haberlo hecho con prisa.

Gracias también por el tiempo que le invertiste a revisar mi código y dar seguimiento. 
Saludos!
